src/urls.py
# coding=utf-8

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines, CreateBarcodeScannEvent
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy

from django.conf import settings

# Admin-Seiten konfigurieren
admin.autodiscover()
# admin.site.unregister((User, Group))

if not settings.DEBUG:
    default_redirect = '/feedback-new/'
else:
    default_redirect = '/veranstalter/'

# Datenbank-Admin und Entwicklerdoku
urlpatterns = [
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    url(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^intern/admin/', include(admin.site.urls)),
]

# allgemeine Views
urlpatterns += [
    url(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}),
]

# öffentliche Views
urlpatterns += [
    url(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    url(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [url(r'^deadlines/$',
                         VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                url(r'^barcodedrop/$',
                         csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),
                ]


# Veranstalter-Views
urlpatterns += [
    url(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    url(r'^veranstalter/$', feedback.views.veranstalter.index, name='veranstalter-index'),
]

urlpatterns += [
    url(r'^veranstalter/verantwortlicherUpdate/$', feedback.views.veranstalter.VerantwortlicherUpdate.as_view(),
        name='VerantwortlicherUpdate'),
    url(r'^veranstalter/freieFragenUpdate/$', feedback.views.veranstalter.FreieFragenUpdate.as_view(),
        name='FreieFragenUpdate'),
    url(r'^veranstalter/kleingruppenUpdate/$', feedback.views.veranstalter.KleingruppenUpdate.as_view(),
        name='KleingruppenUpdate'),
    url(r'^veranstalter/zusammenfassung/$', feedback.views.veranstalter.VeranstaltungZusammenfassung.as_view(),
        name='VeranstaltungZusammenfassung'),
]

# interne Views
urlpatterns += [
    url(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    url(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    url(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    url(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    url(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    url(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    url(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    url(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    url(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),

]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    url(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    url(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    url(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    url(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    url(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    url(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    url(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    url(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': reverse_lazy('public-results')}, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
    url(r'^d120de/(?P<tail>.*)$', feedback.views.redirect,
        {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/feedback/models/base.py
# coding=utf-8

from __future__ import unicode_literals

import random

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.utils import OperationalError
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db.models import Q

from feedback.tools import ean_checksum_calc, ean_checksum_valid
from feedback import auth

from django.utils import formats

import datetime


class Semester(models.Model):
    FRAGEBOGEN_CHOICES = (
        ('2008', 'Fragebogen 2008'),
        ('2009', 'Fragebogen 2009'),
        ('2012', 'Fragebogen 2012'),
        ('2016', 'Fragebogen 2016'),

    )
    SICHTBARKEIT_CHOICES = (
        ('ADM', u'Administratoren'),
        ('VER', u'Veranstalter'),
        ('ALL', u'alle (öffentlich)'),
    )

    semester = models.IntegerField(help_text=u'Aufbau: YYYYS, wobei YYYY = Jahreszahl und S = Semester (0=SS, 5=WS).',
                                   unique=True)
    fragebogen = models.CharField(max_length=5, choices=FRAGEBOGEN_CHOICES,
                                  help_text=u'Verwendete Version des Fragebogens.')
    sichtbarkeit = models.CharField(max_length=3, choices=SICHTBARKEIT_CHOICES,
                                    help_text=u'Sichtbarkeit der Evaluationsergebnisse.<br /><em>' +
                                              SICHTBARKEIT_CHOICES[0][1] +
                                              u':</em> nur für Mitglieder des Feedback-Teams<br /><em>' +
                                              SICHTBARKEIT_CHOICES[1][1] +
                                              u':</em> Veranstalter und Mitglieder des Feedback-Teams<br /><em>' +
                                              SICHTBARKEIT_CHOICES[2][1] +
                                              u':</em> alle (beschränkt auf das Uninetz)<br />'
                                    )
    vollerhebung = models.BooleanField(default=False)

    def _format_generic(self, ss, ws, space, modulus):
        sem = self.semester // 10
        if (modulus > 0):
            sem = sem % modulus

        if self.semester % 10 == 0:
            return u'%s%s%d' % (ss, space, sem)
        else:
            return u'%s%s%d/%d' % (ws, space, sem, sem + 1)

    def _format(self, ss, ws):
        return self._format_generic(ss, ws, ' ', 0)

    def short(self):
        return self._format('SS', 'WS')

    def long(self):
        return self._format('Sommersemester', 'Wintersemester')

    def evasys(self):
        return self._format_generic('SS', 'WS', '', 100)

    def last_Auswertungstermin(self):
        """Letzter Tag der als Auswertungstermin angegeben werden kann"""
        year = 0
        moth = 0
        day = 15
        # Sommersemester
        if self.semester % 10 == 0:
            year = self.semester / 10
            month = 10
        # Wintersemester
        else:
            year = (self.semester / 10) + 1
            month = 4

        return datetime.datetime(year, month, day)

    def last_Auswertungstermin_to_late_human(self):
        """Der erste Tag der nach dem letzten Auswertungstermin liegt formatiert"""
        toLateDate = self.last_Auswertungstermin() + datetime.timedelta(days=1)
        return formats.date_format(toLateDate, 'DATE_FORMAT')

    def auswertungstermin_years(self):
        """Die Jahre in denen der Auswertungstermin liegen kann"""
        return self.last_Auswertungstermin().year,

    def __unicode__(self):
        return self.long()

    class Meta:
        verbose_name = 'Semester'
        verbose_name_plural = 'Semester'
        ordering = ['-semester']
        app_label = 'feedback'

    @staticmethod
    def current():
        try:
            return Semester.objects.order_by('-semester')[0]
        except IndexError:
            return None
        except OperationalError:
            return None


class Person(models.Model):
    GESCHLECHT_CHOICES = (
        ('', ''),
        ('m', 'Herr'),
        ('w', 'Frau'),
    )

    GESCHLECHT_EVASYS_XML = {
        '': '',
        'm': 'm',
        'w': 'f',
    }

    geschlecht = models.CharField(max_length=1, choices=GESCHLECHT_CHOICES, blank=True, verbose_name=u'Anrede')
    vorname = models.CharField(_('first name'), max_length=30, blank=True)
    nachname = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('e-mail address'), blank=True)
    anschrift = models.CharField(_('anschrift'), max_length=80, blank=True,
                                 help_text='Bitte geben sie die Anschrift so an, dass der Versand per Hauspost problemlos erfolgen kann.')
    fachgebiet = models.CharField(_('Fachgebiet'), max_length=80, blank=True)

    def full_name(self):
        return u'%s %s' % (self.vorname, self.nachname)

    def get_evasys_key(self):
        return "pe-%s" % self.id

    def get_evasys_geschlecht(self):
        return Person.GESCHLECHT_EVASYS_XML[self.geschlecht]

    def __unicode__(self):
        return u'%s, %s' % (self.nachname, self.vorname)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'Personen'
        ordering = 'nachname', 'vorname'
        app_label = 'feedback'

    @staticmethod
    def create_from_import_person(ip):
        # Prüfen, ob Benutzer existiert
        try:
            return Person.objects.filter(vorname=ip.vorname, nachname=ip.nachname)[0]
        except (Person.DoesNotExist, IndexError):
            try:
                return AlternativVorname.objects.filter(vorname=ip.vorname).get().person
            except (AlternativVorname.DoesNotExist, IndexError):
                return Person.objects.create(vorname=ip.vorname, nachname=ip.nachname)

    @staticmethod
    def persons_to_edit(semester=None):
        if semester is None:
            semester = Semester.current()
        return Person.objects.filter(Q(geschlecht='') | Q(email=''), veranstaltung__semester=semester)\
            .order_by('id').distinct()

    @staticmethod
    def all_edited_persons():
        return Person.objects.filter(~Q(geschlecht='') & ~Q(email='')).order_by('id').distinct()

    @staticmethod
    def persons_with_similar_names(vorname, nachname):
        return Person.all_edited_persons().filter(vorname__startswith=vorname, nachname=nachname)

    @staticmethod
    def veranstaltungen(person):
        return Veranstaltung.objects.filter(veranstalter=person)

    @staticmethod
    def replace_veranstalter(new, old):
        veranstaltungen = Person.veranstaltungen(new)

        # replace every lecture held by 'new' with 'old'
        for v in veranstaltungen:
            v.veranstalter = [old]
            v.save()

        # save the second name from 'new' as the alternative first name of 'old'
        av = AlternativVorname.objects.create(vorname=new.vorname, person=old)
        av.save()

    @staticmethod
    def is_veranstalter(person):
        return Person.veranstaltungen(person).count() > 0


class AlternativVorname(models.Model):
    vorname = models.CharField(_('first name'), max_length=30, blank=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Veranstaltung(models.Model):
    TYP_CHOICES = (
        ('v', 'Vorlesung'),
        ('vu', 'Vorlesung mit Übung'),
        ('pr', 'Praktikum'),
        ('se', 'Seminar'),
    )

    SPRACHE_CHOICES = (
        ('de', 'Deutsch'),
        ('en', 'Englisch'),
    )
    # 0    undefiniert
    # 1    Vorlesung
    # 2    Seminar
    # 3    Proseminar
    # 4    Übung
    # 5    Praktikum
    # 6    Tutorium
    # 7    Sonstige
    # 8    Projekt
    # 9    Vorlesung + Übung
    # 10    Ringvorlesung
    # 11    Vorlesung+Praktikum
    VORLESUNGSTYP = {
        'v': 1,
        'vu': 9,
        'pr': 5,
        'se': 2,
    }

    VORLESUNGSTYP_XML = {
        'v': 'Vorlesung',
        'vu': 'Vorlesung + Übung',
        'pr': 'Praktikum',
        'se': 'Seminar',
    }

    # Bögen 2015

    ## Deutsch
    # PD FB20Pv1 2677
    # SD FB20Sv2 2681
    # ÜD FB20Üv1 2675
    # VD FB20Vv1 2679

    ## Englisch
    # PE FB20Pv1e 2704
    # SE FB20Sv1e 2702
    # ÜE FB20Üv1e 2700
    # VE FB20Vv1e 2698

    EVASYS_BOGENKENNUNG_DE = {
        'pr': 'FB20Pv1',
        'se': 'FB20Sv2',
        'u': 'FB20Üv1',
        'v': 'FB20Vv1',
        'vu': 'FB20Vv1',  # FIXME: Eigentlich zwei Umfragen
    }

    EVASYS_BOGENKENNUNG_EN = {
        'pr': 'FB20Pv1e',
        'se': 'FB20Sv1e',
        'u': 'FB20Üv1e',
        'v': 'FB20Vv1e',
        'vu': 'FB20Vv1e',  # FIXME: Eigentlich zwei Umfragen
    }

    BARCODE_BASE = 2 * 10 ** 11

    # Vorlesungsstatus
    STATUS_ANGELEGT = 100
    STATUS_GEDRUCKT = 600
    STATUS_VERSANDT = 700
    STATUS_BOEGEN_EINGEGANGEN = 800
    STATUS_BOEGEN_GESCANNT = 900

    STATUS_CHOICES = (
        (STATUS_ANGELEGT, 'Angelegt'),
        (STATUS_GEDRUCKT, 'Gedruckt'),
        (STATUS_VERSANDT, 'Versandt'),
        (STATUS_BOEGEN_EINGEGANGEN, 'Bögen eingegangen'),
        (STATUS_BOEGEN_GESCANNT, 'Bögen gescannt')
    )

    STATUS_UEBERGANG = {
        STATUS_ANGELEGT: (STATUS_GEDRUCKT,),
        STATUS_GEDRUCKT: (STATUS_VERSANDT,),
        STATUS_VERSANDT: (STATUS_BOEGEN_EINGEGANGEN,),
        STATUS_BOEGEN_EINGEGANGEN: (STATUS_BOEGEN_GESCANNT,)
    }

    # Helfertext für Dozenten für den Veranstaltungstyp.
    vlNoEx = 'Wenn Ihre Vorlesung keine Übung hat wählen Sie bitte <i>%s</i> aus'
    for cur in TYP_CHOICES:
        if cur[0] == 'v':
            vlNoEx = vlNoEx % cur[1]
            break

    typ = models.CharField(max_length=2, choices=TYP_CHOICES, help_text=vlNoEx)
    name = models.CharField(max_length=150)
    semester = models.ForeignKey(Semester)
    lv_nr = models.CharField(max_length=15, blank=True, verbose_name=u'LV-Nummer')
    status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_ANGELEGT)
    grundstudium = models.BooleanField()
    evaluieren = models.BooleanField()

src/templates/intern/fragebogensprache.html
{% extends "bestellung_base.html" %}

{% block title %}Zuordnung Veranstaltungen zu Sprache des Fragebogens{% endblock %}

{% block content %}
<h1>Zuordnung Veranstaltungen zu Sprache des Fragebogens</h1>

<table class="border">
	<tr>
		<th>Veranstaltung</th>
		<th>Sprache</th>
		<th>Anzahl</th>
		<th>Typ</th>
		<th>gedruckt</th>
		<th>zurück</th>
	</tr>
{% for v in veranstaltungen %}
	<tr class="cycle {% cycle 'row1' 'row2' %}">
		<td>{{v.name}}</td>
		<td>{% if v.sprache %}{{v.get_sprache_display}}{% else %}?{% endif %}</td>
		<td>{{v.anzahl}}</td>
		<td>{{v.typ}}</td>
		<td>[<span style="margin-left:12px;">]</span></td>
		<td>[<span style="margin-left:12px;">]</span></td>
	</tr>
{% endfor %}
</table>
{% endblock %}

src/templates/intern/generate_letters.html
{% extends "bestellung_base.html" %}

{% block title %}Anschreiben erzeugen{% endblock %}

{% block content %}
<h1>Anschreiben erzeugen</h1>

<p>Das Anschreiben ist ein Brief an die Veranstalter, der den Fragebögen beigefügt wird.</p>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
<p>
{% include 'includes/semesterauswahl.html' %}<br />
<label for="abgabedatum">Erhebungswoche:</label> <input type="text" id="erhebungswoche" name="erhebungswoche" value="{{erhebungswoche}}"></input><br />
</p>
<p>Zu erzeugende Datei:
<fieldset>
<input type="radio" id="anschreiben" name="vorlage" value="Anschreiben"><label for="anschreiben"> Anschreiben</label><br>
<input type="radio" id="aufkleber" name="vorlage" value="Aufkleber"><label for="aufkleber"> Aufkleber</label><br>
<input type="radio" id="grosseaufkleber" name="vorlage" value="Grossaufkleber"><label for="grosseaufkleber"> Aufkleber (nur für große Veranstaltungen >= 85)</label><br>
</fieldset>
<p>
<input type="submit" name="submit" value="PDF erzeugen" />
</p>
</form>

{% if texlog %}
<h2>Fehler bei der Ausführung von pdflatex</h2>
<pre>{{texlog}}</pre>
{% endif %}

{% endblock %}

src/templates/intern/import_ergebnisse.html
{% extends "bestellung_base.html" %}

{% block title %}Ergebnisse aus EvaSys importieren{% endblock %}

{% block content %}
<h1>Ergebnisse aus EvaSys importieren</h1>

<p>
Hier können die von EvaSys gescannten und eingelesenen Fragebögen in Form einer CSV-Datei (kann in EvaSys erstellt werden) hochgeladen werden.
</p>

<p>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{% include 'includes/semesterauswahl.html' %}<br />
{{ form }}
<input type="submit" name="submit" value="Hochladen" /> 
</form>
</p>
{% endblock %}

src/templates/intern/import_vv.html
{% extends "bestellung_base.html" %}

{% block title %}Vorlesungsverzeichnis importieren{% endblock %}

{% block content %}
<h1>Vorlesungsverzeichnis importieren</h1>

<p>Das System erwartet eine XML-Datei, die aus TUCaN exportiert wurde und alle Veranstaltungen des Semesters enthält.</p>
<p>Achtung: Upload und serverseitige Verarbeitung der Datei können aufgrund der großen Datenmenge etwas dauern.</p>
<p>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form }}
<input type="submit" name="submit" value="Hochladen" /> 
</form>
</p>
<p><b>Hinweis</b> von Wolfgang Heenes, wie man mit Zugriff auf TUCaN (z.B. als Mitarbeiter des Studienbüros) diese Daten im passenden Format erhält, falls er mal nicht mehr dafür zuständig ist:<br />
<i>"Die Daten kommen aus dem Backend (Semesterangebot -> Vorlesungsverzeichnis erstellen). Es gibt auf dem Sharepoint KEINEN Report, der das KOMPLETTE Vorlesungsverzeichnis enthält."</i></p>
{% endblock %}

src/templates/intern/import_vv_edit.html
{% extends "bestellung_base.html" %}{% load static %}{% load filter_range %}

{% block extra_header %}
<link rel="stylesheet" type="text/css" href="{% static 'jquery/jquery-ui-1.8.6.custom.css' %}" />
<style type="text/css">
h2.ui-accordion-header, h3.ui-accordion-header, h4.ui-accordion-header,
h5.ui-accordion-header h6.ui-accordion-header
{ margin-bottom: 0 }

.mark_unmark { margin-bottom: 0.9em; margin-top: -0.9em; font-size: 80% }

.foo { border: 1px solid green; }
.unattended_course {
    background-color: #FFFF00;
}
</style>

<script type="text/javascript" src="{% static 'jquery/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery/jquery-ui-1.8.6.custom.min.js' %}"></script>
<script type="text/javascript">
<!--
function check_checkboxes(event, checked) {
	var parentElem = $(event.target).parent().parent();

    var checkboxes;
    if(checked) {
        checkboxes = parentElem.find(".attended_course > input:checkbox");
        var unattended_courses = parentElem.find(".unattended_course");
        if(unattended_courses.length > 0) {
            alert("Es gibt Veranstaltungen ohne validen Dozenten. Diese Veranstaltungen wurden nicht ausgewählt.");

            var expandParent = function(childElem) {
                var accordeon_div = childElem.parent().parent();
                var accordeon_title = accordeon_div.prev();
                if(accordeon_title.is("h3")) {
                    if(!accordeon_div.is(":visible")) { // only expand if collapsed
                        accordeon_title.click();
                    }
                    expandParent(accordeon_title);
                }
            }
            expandParent(unattended_courses.eq(0))
        }
    } else {
        checkboxes = parentElem.find("input:checkbox");
    }
    checkboxes.attr('checked', checked);
	event.preventDefault();	
}

$(function() {
	$(".accordion").accordion({ autoHeight: false, collapsible: true, active: false });
	
	$("a.markall").click(function(event) { check_checkboxes(event, true); });
	$("a.unmarkall").click(function(event) { check_checkboxes(event, false); });
});
//-->
</script>
{% endblock %}
	
{% block title %}Vorlesungsverzeichnis importieren{% endblock %}

{% block content %}
<h1>Vorlesungsverzeichnis importieren</h1>

<noscript>
	<p>Bitte JavaScript aktivieren, um bequemer durch das Verzeichnis navigieren und Veranstaltungen auswählen zu können!</p>
</noscript>

<p>Im Folgenden können die zu importierenden Veranstaltungen ausgewählt werden.</p>

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        {% include 'includes/semesterauswahl.html' %}<br />
        Falls das Semester, für das Veranstaltungen importiert werden sollen, nicht in der Auswahlliste steht, muss es zunächst über die Datenbank-Administration hinzugefügt werden.
    </p>

    {% for category in vv %}
        {% if forloop.counter0 == 0 or category.rel_level > 0 %}
            <div class="accordion"> {# Create sub-category #}
        {% else %}
            {% if category.rel_level == 0 %}
                </div> {# Close previous accordion-div #}
            {% else %}
                {% if category.rel_level < 0 %}
                    </div> {# Close previous accordion-div #}
                    {% for i in category.rel_level|range:0 %}
                        </div></div> {# Jump to parent-category #}
                    {% endfor %}
                {% endif %}
            {% endif %}
        {% endif %}

        <h3><a href="#">{{ category.name }}</a></h3>
        <div>
            <div class="mark_unmark"><a href="#" class="markall">Alle markieren</a> | <a href="#" class="unmarkall">Markierungen aufheben</a></div>
            <ul>
                {% for iv in category.ivs.all %}
                    <li style="list-style-type: none" class="{{ iv.is_attended_course | yesno:"attended_course,unattended_course" }} ">
                        <input type="checkbox" id="v{{iv.id}}" name="v" value="{{iv.id}}" />
                        <label for="v{{iv.id}}">{{ iv }}</label>
                    </li>
                {% endfor %}
            </ul>

    {% endfor %}
    {% for i in 0|range:remaining_close_tags %}
        </div></div>
    {% endfor %}

    <div>
        <input type="submit" name="submit" value="Weiter" />&nbsp;
        <input type="reset" name="reset" value="Zurücksetzen" />
    </div>
</form>

{% endblock %}

src/templates/intern/index.html
{% extends "bestellung_base.html" %} {% block title %}Interner Bereich{% endblock %} {% block content %}
<h1>Interner Bereich</h1>
<ul>
    <li><a href="{% url 'admin:index' %}" target="_blank">Verwaltung der Daten</a></li>
    <li><a href="{% url 'rechte-uebernehmen' %}">zu Veranstalter-Account wechseln</a></li>
    <li><a href="{% url 'sendmail' %}">Mail an Veranstalter verschicken</a></li>
    <li><a href="{% url 'fragebogensprache' %}">Zuordnung Veranstaltungen zu Fragebogensprache</a></li>
    <li><a href="{% url 'lange_ohne_evaluation' %}">Veranstaltungen die lange nicht mehr evaluiert wurden</a></li>
    <li><a href="{% url 'logout' %}">Ausloggen</a></li>
</ul>
<h3>Status der Rückmeldungen durch die Veranstalter</h3>
<p>Aktuell haben wir {{ruck_veranst}} Rückmeldungen von {{all_veranst}} Veranstaltungen.</p> 
<div style="width:{{width_progressbar}}px; background-color:#eeeeec;">
    <div style="width:{{width_progressbar_success}}px; background-color:#babdb6;">
        <p style="text-align:center;">{{relativ_result|floatformat:-2}}%</p>
    </div>
</div>
<h3>Ablauf</h3>
<p>Dies sind nicht alle nötigen Schritte; siehe <a href="https://www.fachschaft.informatik.tu-darmstadt.de/trac/fs/wiki/Untergruppen/Feedback" target="_blank">Ablauf im Trac</a>.</p>
<ol>
    <li><a href="{% url 'admin:feedback_semester_add' %}" target="_blank">neues Semester anlegen</a> (aktuell: 
    {% if cur_semester %}{{cur_semester.short}}{% else %}nicht Vorhanden{% endif %})</li>
    <li><a href="{% url 'import_vv' %}">Veranstaltungen aus VV importieren</a> (vor Bestellphase)</li>
    <li><a href="{% url 'import_vv_edit_users' %}">Fehlende Personendaten nachtragen</a> (vor Bestellphase)</li>
    <li><a href="{% url 'generate_letters' %}">Anschreiben für Veranstalter erzeugen</a> (nach Bestellphase)</li>
    <li><a href="{% url 'export_veranstaltungen' %}">Veranstaltungen für EvaSys exportieren</a> (vor dem Scannen)</li>
    <li><a href="{% url 'import_ergebnisse' %}">Ergebnisse aus EvaSys importieren</a> (nach dem Scannen)</li>
    <li><a href="{% url 'sync_ergebnisse' %}">Rankings berechnen</a> (nach dem Ergebnis-Import)</li>
    {% if cur_semester %}
    <li><a href="{% url 'admin:feedback_semester_change' cur_semester.id %}" target="_blank">Ergebnisse veröffentlichen</a> (aktuell: sichtbar für {{cur_semester.get_sichtbarkeit_display}})</li>
    {% endif %}
</ol>
{% endblock %}

{% block backlink %}<!-- kein Backlink -->{% endblock %}