src/urls.py
# coding=utf-8

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import feedback.views.public
import feedback.views.veranstalter
from feedback.views.public_class_view import VeranstaltungsDeadlines, CreateBarcodeScannEvent
import feedback.views.intern
import feedback.views.intern.vv
import feedback.views.intern.auth
from django.views.decorators.csrf import csrf_exempt
import django.contrib.auth.views
from django.urls import reverse_lazy

from django.conf import settings

# Admin-Seiten konfigurieren
admin.autodiscover()
# admin.site.unregister((User, Group))

if not settings.DEBUG:
    default_redirect = '/feedback-new/'
else:
    default_redirect = '/veranstalter/'

# Datenbank-Admin und Entwicklerdoku
urlpatterns = [
    # Muss in dieser Reihenfolge stehen bleiben, da sonst /doc nicht funktioniert!
    url(r'^intern/admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^intern/admin/', include(admin.site.urls)),
]

# allgemeine Views
urlpatterns += [
    url(r'^$', feedback.views.redirect, {'redirect_to': default_redirect}),
]

# öffentliche Views
urlpatterns += [
    url(r'^ergebnisse/(?P<vid>\d+)/$', feedback.views.public.veranstaltung, name='public-veranstaltung'),
    url(r'^ergebnisse/$', feedback.views.public.index, name='public-results'),
]

urlpatterns += [url(r'^deadlines/$',
                         VeranstaltungsDeadlines.as_view(), name='Deadlines'),
                url(r'^barcodedrop/$',
                         csrf_exempt(feedback.views.public.barcodedrop), name='barcodedrop'),
                ]


# Veranstalter-Views
urlpatterns += [
    url(r'^veranstalter/login/$', feedback.views.veranstalter.login, name='veranstalter-login'),
    url(r'^veranstalter/$', feedback.views.veranstalter.index, name='veranstalter-index'),
]

urlpatterns += [
    url(r'^veranstalter/verantwortlicherUpdate/$', feedback.views.veranstalter.VerantwortlicherUpdate.as_view(),
        name='VerantwortlicherUpdate'),
    url(r'^veranstalter/freieFragenUpdate/$', feedback.views.veranstalter.FreieFragenUpdate.as_view(),
        name='FreieFragenUpdate'),
    url(r'^veranstalter/kleingruppenUpdate/$', feedback.views.veranstalter.KleingruppenUpdate.as_view(),
        name='KleingruppenUpdate'),
    url(r'^veranstalter/zusammenfassung/$', feedback.views.veranstalter.VeranstaltungZusammenfassung.as_view(),
        name='VeranstaltungZusammenfassung'),
]

# interne Views
urlpatterns += [
    url(r'^intern/uebersicht/$', feedback.views.intern.index, name='intern-index'),
    url(r'^intern/sendmail/$', feedback.views.intern.sendmail, name='sendmail'),
    url(r'^intern/export_veranstaltungen/$', feedback.views.intern.export_veranstaltungen, name='export_veranstaltungen'),
    url(r'^intern/generate_letters/$', feedback.views.intern.generate_letters, name='generate_letters'),
    url(r'^intern/import_ergebnisse/$', feedback.views.intern.import_ergebnisse, name='import_ergebnisse'),
    url(r'^intern/sync_ergebnisse/$', feedback.views.intern.sync_ergebnisse, name='sync_ergebnisse'),
    url(r'^intern/fragebogensprache/$', feedback.views.intern.fragebogensprache, name='fragebogensprache'),
    url(r'^intern/lange_ohne_evaluation/$', feedback.views.intern.lange_ohne_evaluation, name='lange_ohne_evaluation'),
    url(r'^intern/ergebnisse/$', feedback.views.intern.ergebnisse, name='intern-ergebnisse'),

]

# interne Views: Vorlesungsverzeichnis
urlpatterns += [
    url(r'^intern/import_vv/$', feedback.views.intern.vv.import_vv, name='import_vv'),
    url(r'^intern/import_vv_edit/$', feedback.views.intern.vv.import_vv_edit, name='import_vv_edit'),
    url(r'^intern/import_vv_edit_users/$', feedback.views.intern.vv.PersonFormView.as_view(),
        name='import_vv_edit_users'),
    url(r'^intern/import_vv_edit_users/(?P<pk>\d+)/$', feedback.views.intern.vv.PersonFormUpdateView.as_view(),
        name='import_vv_edit_users_update'),
    url(r'^intern/import_vv_edit_users/(?P<pk>\d+)/namecheck/$', feedback.views.intern.vv.SimilarNamesView.as_view(),
        name='import_vv_edit_users_update_namecheck')
]

# interne Views: Authentifizierung
urlpatterns += [
    url(r'^intern/rechte_uebernehmen/$', feedback.views.intern.auth.rechte_uebernehmen, name='rechte-uebernehmen'),
    url(r'^intern/rechte_zuruecknehmen/$', feedback.views.intern.auth.rechte_zuruecknehmen, name='rechte_zuruecknehmen'),
    url(r'^intern/$', feedback.views.intern.auth.login, name='auth-login'),
]

# Logout
urlpatterns += [
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': reverse_lazy('public-results')}, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # Ausschließlich in der Entwicklung nötig, damit statische Dateien (JS, CSS, Bilder...)
    # angezeigt werden. Im Server-Betrieb kümmert sich Apache darum.
    urlpatterns += [
    url(r'^d120de/(?P<tail>.*)$', feedback.views.redirect,
        {'redirect_to': 'http://www.d120.de/d120de/'}),
    ]

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/feedback/models/base.py
# coding=utf-8

from __future__ import unicode_literals

import random

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.utils import OperationalError
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db.models import Q

from feedback.tools import ean_checksum_calc, ean_checksum_valid
from feedback import auth

from django.utils import formats

import datetime


class Semester(models.Model):
    FRAGEBOGEN_CHOICES = (
        ('2008', 'Fragebogen 2008'),
        ('2009', 'Fragebogen 2009'),
        ('2012', 'Fragebogen 2012'),
        ('2016', 'Fragebogen 2016'),

    )
    SICHTBARKEIT_CHOICES = (
        ('ADM', u'Administratoren'),
        ('VER', u'Veranstalter'),
        ('ALL', u'alle (öffentlich)'),
    )

    semester = models.IntegerField(help_text=u'Aufbau: YYYYS, wobei YYYY = Jahreszahl und S = Semester (0=SS, 5=WS).',
                                   unique=True)
    fragebogen = models.CharField(max_length=5, choices=FRAGEBOGEN_CHOICES,
                                  help_text=u'Verwendete Version des Fragebogens.')
    sichtbarkeit = models.CharField(max_length=3, choices=SICHTBARKEIT_CHOICES,
                                    help_text=u'Sichtbarkeit der Evaluationsergebnisse.<br /><em>' +
                                              SICHTBARKEIT_CHOICES[0][1] +
                                              u':</em> nur für Mitglieder des Feedback-Teams<br /><em>' +
                                              SICHTBARKEIT_CHOICES[1][1] +
                                              u':</em> Veranstalter und Mitglieder des Feedback-Teams<br /><em>' +
                                              SICHTBARKEIT_CHOICES[2][1] +
                                              u':</em> alle (beschränkt auf das Uninetz)<br />'
                                    )
    vollerhebung = models.BooleanField(default=False)

    def _format_generic(self, ss, ws, space, modulus):
        sem = self.semester // 10
        if (modulus > 0):
            sem = sem % modulus

        if self.semester % 10 == 0:
            return u'%s%s%d' % (ss, space, sem)
        else:
            return u'%s%s%d/%d' % (ws, space, sem, sem + 1)

    def _format(self, ss, ws):
        return self._format_generic(ss, ws, ' ', 0)

    def short(self):
        return self._format('SS', 'WS')

    def long(self):
        return self._format('Sommersemester', 'Wintersemester')

    def evasys(self):
        return self._format_generic('SS', 'WS', '', 100)

    def last_Auswertungstermin(self):
        """Letzter Tag der als Auswertungstermin angegeben werden kann"""
        year = 0
        moth = 0
        day = 15
        # Sommersemester
        if self.semester % 10 == 0:
            year = self.semester / 10
            month = 10
        # Wintersemester
        else:
            year = (self.semester / 10) + 1
            month = 4

        return datetime.datetime(year, month, day)

    def last_Auswertungstermin_to_late_human(self):
        """Der erste Tag der nach dem letzten Auswertungstermin liegt formatiert"""
        toLateDate = self.last_Auswertungstermin() + datetime.timedelta(days=1)
        return formats.date_format(toLateDate, 'DATE_FORMAT')

    def auswertungstermin_years(self):
        """Die Jahre in denen der Auswertungstermin liegen kann"""
        return self.last_Auswertungstermin().year,

    def __unicode__(self):
        return self.long()

    class Meta:
        verbose_name = 'Semester'
        verbose_name_plural = 'Semester'
        ordering = ['-semester']
        app_label = 'feedback'

    @staticmethod
    def current():
        try:
            return Semester.objects.order_by('-semester')[0]
        except IndexError:
            return None
        except OperationalError:
            return None


class Person(models.Model):
    GESCHLECHT_CHOICES = (
        ('', ''),
        ('m', 'Herr'),
        ('w', 'Frau'),
    )

    GESCHLECHT_EVASYS_XML = {
        '': '',
        'm': 'm',
        'w': 'f',
    }

    geschlecht = models.CharField(max_length=1, choices=GESCHLECHT_CHOICES, blank=True, verbose_name=u'Anrede')
    vorname = models.CharField(_('first name'), max_length=30, blank=True)
    nachname = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('e-mail address'), blank=True)
    anschrift = models.CharField(_('anschrift'), max_length=80, blank=True,
                                 help_text='Bitte geben sie die Anschrift so an, dass der Versand per Hauspost problemlos erfolgen kann.')
    fachgebiet = models.CharField(_('Fachgebiet'), max_length=80, blank=True)

    def full_name(self):
        return u'%s %s' % (self.vorname, self.nachname)

    def get_evasys_key(self):
        return "pe-%s" % self.id

    def get_evasys_geschlecht(self):
        return Person.GESCHLECHT_EVASYS_XML[self.geschlecht]

    def __unicode__(self):
        return u'%s, %s' % (self.nachname, self.vorname)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'Personen'
        ordering = 'nachname', 'vorname'
        app_label = 'feedback'

    @staticmethod
    def create_from_import_person(ip):
        # Prüfen, ob Benutzer existiert
        try:
            return Person.objects.filter(vorname=ip.vorname, nachname=ip.nachname)[0]
        except (Person.DoesNotExist, IndexError):
            try:
                return AlternativVorname.objects.filter(vorname=ip.vorname).get().person
            except (AlternativVorname.DoesNotExist, IndexError):
                return Person.objects.create(vorname=ip.vorname, nachname=ip.nachname)

    @staticmethod
    def persons_to_edit(semester=None):
        if semester is None:
            semester = Semester.current()
        return Person.objects.filter(Q(geschlecht='') | Q(email=''), veranstaltung__semester=semester)\
            .order_by('id').distinct()

    @staticmethod
    def all_edited_persons():
        return Person.objects.filter(~Q(geschlecht='') & ~Q(email='')).order_by('id').distinct()

    @staticmethod
    def persons_with_similar_names(vorname, nachname):
        return Person.all_edited_persons().filter(vorname__startswith=vorname, nachname=nachname)

    @staticmethod
    def veranstaltungen(person):
        return Veranstaltung.objects.filter(veranstalter=person)

    @staticmethod
    def replace_veranstalter(new, old):
        veranstaltungen = Person.veranstaltungen(new)

        # replace every lecture held by 'new' with 'old'
        for v in veranstaltungen:
            v.veranstalter = [old]
            v.save()

        # save the second name from 'new' as the alternative first name of 'old'
        av = AlternativVorname.objects.create(vorname=new.vorname, person=old)
        av.save()

    @staticmethod
    def is_veranstalter(person):
        return Person.veranstaltungen(person).count() > 0


class AlternativVorname(models.Model):
    vorname = models.CharField(_('first name'), max_length=30, blank=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Veranstaltung(models.Model):
    TYP_CHOICES = (
        ('v', 'Vorlesung'),
        ('vu', 'Vorlesung mit Übung'),
        ('pr', 'Praktikum'),
        ('se', 'Seminar'),
    )

    SPRACHE_CHOICES = (
        ('de', 'Deutsch'),
        ('en', 'Englisch'),
    )
    # 0    undefiniert
    # 1    Vorlesung
    # 2    Seminar
    # 3    Proseminar
    # 4    Übung
    # 5    Praktikum
    # 6    Tutorium
    # 7    Sonstige
    # 8    Projekt
    # 9    Vorlesung + Übung
    # 10    Ringvorlesung
    # 11    Vorlesung+Praktikum
    VORLESUNGSTYP = {
        'v': 1,
        'vu': 9,
        'pr': 5,
        'se': 2,
    }

    VORLESUNGSTYP_XML = {
        'v': 'Vorlesung',
        'vu': 'Vorlesung + Übung',
        'pr': 'Praktikum',
        'se': 'Seminar',
    }

    # Bögen 2015

    ## Deutsch
    # PD FB20Pv1 2677
    # SD FB20Sv2 2681
    # ÜD FB20Üv1 2675
    # VD FB20Vv1 2679

    ## Englisch
    # PE FB20Pv1e 2704
    # SE FB20Sv1e 2702
    # ÜE FB20Üv1e 2700
    # VE FB20Vv1e 2698

    EVASYS_BOGENKENNUNG_DE = {
        'pr': 'FB20Pv1',
        'se': 'FB20Sv2',
        'u': 'FB20Üv1',
        'v': 'FB20Vv1',
        'vu': 'FB20Vv1',  # FIXME: Eigentlich zwei Umfragen
    }

    EVASYS_BOGENKENNUNG_EN = {
        'pr': 'FB20Pv1e',
        'se': 'FB20Sv1e',
        'u': 'FB20Üv1e',
        'v': 'FB20Vv1e',
        'vu': 'FB20Vv1e',  # FIXME: Eigentlich zwei Umfragen
    }

    BARCODE_BASE = 2 * 10 ** 11

    # Vorlesungsstatus
    STATUS_ANGELEGT = 100
    STATUS_GEDRUCKT = 600
    STATUS_VERSANDT = 700
    STATUS_BOEGEN_EINGEGANGEN = 800
    STATUS_BOEGEN_GESCANNT = 900

    STATUS_CHOICES = (
        (STATUS_ANGELEGT, 'Angelegt'),
        (STATUS_GEDRUCKT, 'Gedruckt'),
        (STATUS_VERSANDT, 'Versandt'),
        (STATUS_BOEGEN_EINGEGANGEN, 'Bögen eingegangen'),
        (STATUS_BOEGEN_GESCANNT, 'Bögen gescannt')
    )

    STATUS_UEBERGANG = {
        STATUS_ANGELEGT: (STATUS_GEDRUCKT,),
        STATUS_GEDRUCKT: (STATUS_VERSANDT,),
        STATUS_VERSANDT: (STATUS_BOEGEN_EINGEGANGEN,),
        STATUS_BOEGEN_EINGEGANGEN: (STATUS_BOEGEN_GESCANNT,)
    }

    # Helfertext für Dozenten für den Veranstaltungstyp.
    vlNoEx = 'Wenn Ihre Vorlesung keine Übung hat wählen Sie bitte <i>%s</i> aus'
    for cur in TYP_CHOICES:
        if cur[0] == 'v':
            vlNoEx = vlNoEx % cur[1]
            break

    typ = models.CharField(max_length=2, choices=TYP_CHOICES, help_text=vlNoEx)
    name = models.CharField(max_length=150)
    semester = models.ForeignKey(Semester)
    lv_nr = models.CharField(max_length=15, blank=True, verbose_name=u'LV-Nummer')
    status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_ANGELEGT)
    grundstudium = models.BooleanField()
    evaluieren = models.BooleanField()

src/feedback/models/imports.py
# coding=utf-8

from django.db import models

from feedback.models import Veranstaltung


class ImportPerson(models.Model):
    vorname = models.CharField(max_length=30)
    nachname = models.CharField(max_length=30)

    def full_name(self):
        return u'%s %s' % (self.vorname, self.nachname)

    def __unicode__(self):
        return u'%s, %s' % (self.nachname, self.vorname)

    class Meta:
        verbose_name = 'Importierte Person'
        verbose_name_plural = verbose_name + 'en'
        app_label = 'feedback'


class ImportCategory(models.Model):
    name = models.CharField(max_length=150)

    # gibt die rekursionstiefe im baum an.
    # nullable, um root-Kategorie besonders zu behandeln
    rel_level = models.IntegerField(null=True, default=0)

    # um eindeutige Suche nach Kategorie zu ermoeglichen
    parent = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Importierte Kategorie'
        verbose_name_plural = verbose_name + 'n'
        app_label = 'feedback'
        unique_together = ('parent', 'name')


class ImportVeranstaltung(models.Model):
    typ = models.CharField(max_length=1, choices=Veranstaltung.TYP_CHOICES)
    name = models.CharField(max_length=150)
    lv_nr = models.CharField(max_length=15, blank=True)
    veranstalter = models.ManyToManyField(ImportPerson, blank=True)
    category = models.ForeignKey(ImportCategory, related_name="ivs")
    is_attended_course = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s (%s)' % (self.name, self.lv_nr)

    class Meta:
        verbose_name = 'Importierte Veranstaltung'
        verbose_name_plural = verbose_name + 'en'
        unique_together = ('name', 'lv_nr', 'category')
        app_label = 'feedback'

src/templates/feedback/CreateBarcodeScannEvent.html
<form action="" method="post">
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>

src/templates/feedback/VeranstaltungsDeadlines.html
{% extends "d120_base.html" %}{% load i18n %}
{% block title %}{% trans "Auswertungstermine für das aktuelle Semester" %}{% endblock %}
{% block content %}
    <h2>{% trans "Auswertungstermine für das aktuelle Semester" %}</h2>
    <p>{% trans "Dein ausgefüllter Fragebogen muss bis zu diesem Tag in der Fachschaft eingegangen sein, damit er erfasst wird." %}</p>
    <ul>
        {% for veranstaltung in object_list %}
            <li>{{ veranstaltung.name }}: {{ veranstaltung.auswertungstermin }}</li>
        {% endfor %}
    </ul>
{% endblock %}

src/templates/feedback/person_form.html
{% extends "bestellung_base.html" %}

{% block title %}Veranstalterbereich{% endblock %}

{% block content %}

<p>
	eingeloggt für <strong>{{veranstaltung.name}} ({{veranstaltung.semester.short}})</strong><br />
	<a href="{% url 'django.contrib.auth.views.logout' %}">ausloggen</a>
</p>

<h2>Fragebogenbestellung Schritt 2 von 5</h2>
<h3>Ablauf</h3>
<ol>
<li>Basisdaten</li>
<li><strong>Datenüberprüfung</strong></li>
<li>Freie Fragen</li>
<li>Details zur Übung</li>
<li>Zusammenfassung</li>
</ol>
<h3>Datenüberprüfung</h3>

<p>Bitte überprüfen Sie jetzt die Daten des Verantwortlichen <strong>{{ veranstaltung.verantwortlich }}</strong> 
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="weiter" />
</form>
{% endblock %}

{% block backlink %}<!-- kein Backlink -->{% endblock %}

src/templates/feedback/veranstaltung_freie_fragen_form.html
{% extends "bestellung_base.html" %}{% load staticfiles %}

{% block title %}Veranstalterbereich{% endblock %}

{% block content %}

<p>
	eingeloggt für <strong>{{veranstaltung.name}} ({{veranstaltung.semester.short}})</strong><br />
	<a href="{% url 'django.contrib.auth.views.logout' %}">ausloggen</a>
</p>

<h2>Fragebogenbestellung Schritt 3 von 5</h2>
<h3>Ablauf</h3>
<ol>
<li>Basisdaten</li>
<li>Datenüberprüfung</li>
<li><strong>Freie Fragen</strong></li>
<li>Details zur Übung</li>
<li>Zusammenfassung</li>
</ol>
<h3>Freie Fragen</h3>
<img src="{% static "img/freiefragen.png" %}" alt="Freie Fragen Feld" width="600" height="71"/>

<p>Auf dem Fragebogen zu Ihrer Veranstaltung können Sie bis zu 
zwei selbst formulierte Fragen an die Studierenden stellen. 
Die Studierenden können jede der Fragen mit einem von fünf Werten zwischen 
&bdquo;<i>trifft zu</i>&ldquo; und &bdquo;<i>trifft nicht zu</i>&ldquo; beantworten.</p>

<p>
Bitte geben Sie hier Ihre freien Fragen ein. Falls Sie keine eigenen Fragen 
stellen möchten, klicken Sie einfach auf weiter.</p>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="weiter" />
</form>
{% endblock %}

{% block backlink %}<!-- kein Backlink -->{% endblock %}

src/templates/feedback/veranstaltung_kleingruppen.html
{% extends "bestellung_base.html" %}{% load staticfiles %}

{% block title %}Veranstalterbereich{% endblock %}

{% block content %}

<p>
	eingeloggt für <strong>{{veranstaltung.name}} ({{veranstaltung.semester.short}})</strong><br />
	<a href="{% url 'django.contrib.auth.views.logout' %}">ausloggen</a>
</p>

<h2>Fragebogenbestellung Schritt 4 von 5</h2>
<h3>Ablauf</h3>
<ol>
<li>Basisdaten</li>
<li>Datenüberprüfung</li>
<li>Freie Fragen</li>
<li><strong>Details zur Übung</strong></li>
<li>Zusammenfassung</li>
</ol>
<h3>Details zur Übung</h3>

<p>Der Fragebögen zur Übung enthält tutorenspezifische Fragen.
Die Antworten können für jeden Tutor bzw. Übungsgruppe individuell ausgewertet werden.
Hierfür benötigen wir Vor- und Nachname des Tutors, die E-Mail Adresse des Tutors, sowie Termin und Raum der Übungsgruppe.</p>
<p>
Vor- und Nachname des Tutors sowie Termin und Raum der Übungsgruppe werden für die eindeutige Zuordnung einer Kennziffer benötigt. Die E-Mail Adresse wird für den Versand der Ergebnisse an den Tutor benötigt.
</p>
<p>
Bitte geben Sie die Daten kommasepartiert in der Reihenfolge <br /><strong>Nachname, Vorname, E-Mail Adresse, Termin und Raum bzw. Anmerkung</strong><br /> an und nutzen Sie für jede Übungsgruppe eine <strong>neue Zeile</strong>.
Anschließend ordnen wir jeder Zeile eine Kennziffer zwischen 1 und 60 zu.
</p>
<h4>Beispiel</h4>
<p style="font-size:10pt;font-family:Monospace;text-align: justify;">
Wulf,Jan,JanWulf@einrot.com,Montag 08:00Uhr S103/109<br />
Mayer,Jörg,JorgMayer@einrot.com,Mittwoch 11:40Uhr S103/126<br />
Baader,Sabine,SabineBaader@superrito.com,Montag 9:50Uhr S115/020<br />
Beich,Matthias,MatthiasBeich@dayrep.com,Mittwoch 11:40Uhr S215/204K<br />
Achen,Tobias,TobiasAchen@jourrapide.com,Dienstag 16:10Uhr S202/C120</p>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="weiter" />
</form>
{% endblock %}

{% block backlink %}<!-- kein Backlink -->{% endblock %}

src/templates/feedback/veranstaltung_zusamenfassung.html
{% extends "bestellung_base.html" %}{% load staticfiles %} {% block title %}Veranstalterbereich{% endblock %} {% block content %}

<p>
	eingeloggt für <strong>{{veranstaltung.name}} ({{veranstaltung.semester.short}})</strong><br />
	<a href="{% url 'django.contrib.auth.views.logout' %}">ausloggen</a>
</p>

<h2>Fragebogenbestellung Schritt 5 von 5</h2>
<h3>Ablauf</h3>
<ol>
	<li>Basisdaten</li>
	<li>Datenüberprüfung</li>
	<li>Freie Fragen</li>
	<li>Details zur Übung{% if not object.has_uebung %} (Übersprungen){% endif %}</li>
	<li><strong>Zusammenfassung</strong></li>
</ol>
{% if not object.has_uebung %}
<h2>Hinweis</h2>
<p>Schritt 4 wurde übersprungen, da Ihre Veranstaltung keine Übung hat.</p>
{% endif %}
<h2>Zusammenfassung Ihrer Bestellung</h2>
<p>Folgende Daten wurden gespeichert:</p>

<ul>
	<li>Veranstaltungsname: {{ object.name }}</li>
	<li>Typ: {{ object.get_typ_display }}</li>
	<li>Sprache der Fragebögen: {{ object.get_sprache_display }}</li>
	<li>Anzahl der Fragebögen: {{ object.anzahl }}{% if object.has_uebung %} * 2 (Für Vorlesung und Übung werden getrennte Bögen verschickt){% endif %}</li>
	<li>Verantwortlich:
		<ul>
			<li>Name: {{ object.verantwortlich }}</li>
			<li>Anschrift: {{ object.verantwortlich.anschrift }}</li>
			<li>Fachgebiet: {{ object.verantwortlich.fachgebiet }}</li>
		</ul>
	</li>
	<li>Empfänger der Ergebnisse:
		<ul>{% for empf in object.ergebnis_empfaenger.all %}
			<li>{{ empf }}</li>
			{% endfor %}</ul>
	</li>
	<li>1. Freie Frage: {{ object.freiefrage1|default:"Keine Frage angegeben" }}</li>
	<li>2. Freie Frage: {{ object.freiefrage2|default:"Keine Frage angegeben" }}</li>
	{% if object.has_uebung %}
	<li>Kleingruppen: {{ object.kleingruppen|linenumbers|linebreaks}}</li>{% endif %}
</ul>
<p>Vielen Dank, Ihre Bestellung wurde gespeichert! Sie können sich jetzt <a href="{% url 'django.contrib.auth.views.logout' %}">ausloggen</a>.</p>
<p><a href="{% url 'veranstalter-index' %}">Daten der Bestellung ändern.</a></p>
{% endblock %} {% block backlink %}
<!-- kein Backlink -->{% endblock %}